# Used for Netlify CMS admin
backend:
  name: github
  branch: master
  repo: jonthornton15/pro-gatsby-2

site_url: https://hopeful-wilson-30e011.netlify.com

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "Team"
    folder: src/team
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Team Member", name: "title", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
